const {test,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path'),AxeBuilder=require('@axe-core/playwright').default;
const {ready,configure,fill,normalizeRequests}=require('./helpers/screenprint-customer-browser'),{snapshot,check}=require('./helpers/specialty-calculators-browser');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,'screenshots/css-unification'),original=process.env.CAPTURE_SPECIALTY_CALCULATORS_ORIGINAL==='1',phase=original?'original':'current';
test.use({timezoneId:'America/Los_Angeles',locale:'en-US',reducedMotion:'reduce'});test.setTimeout(120000);
function record(name,value){const file='tests/fixtures/specialty-calculators-screenprint-customer-'+name+'-original-browser.json',full=path.join(root,file);if(original&&!fs.existsSync(full)){fs.writeFileSync(full,JSON.stringify(value,null,2)+'\n');fs.appendFileSync(path.join(root,'ACTIVE_FILES.md'),'\n- '+file+' — immutable synthetic customer-supplied screen-print presentation, financial and request evidence.\n');}else expect(value).toEqual(JSON.parse(fs.readFileSync(full,'utf8')));}
async function assets(page){await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].filter(n=>n.getClientRects().length).map(n=>n.decode().catch(()=>{})));});expect(await page.locator('img').evaluateAll(ns=>ns.filter(n=>n.getClientRects().length&&(!n.complete||!n.naturalWidth)).map(n=>n.src))).toEqual([]);}
async function submit(page){await page.locator('#submitQuoteBtn').click();await expect.poll(()=>page.locator('#submitQuoteBtn').isEnabled()).toBe(true);}
async function evidence(page,name,events){const states=[];fs.mkdirSync(out,{recursive:true});for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await assets(page);await page.evaluate(()=>scrollTo(0,0));const state=await snapshot(page),axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();states.push({width,...state,violations:axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});await page.screenshot({path:path.join(out,'specialty-calculators-screenprint-customer-'+name+'-'+phase+'-'+width+'.png'),fullPage:true});}
 check(expect,events);record(name,{states,calculation:await page.evaluate(()=>window.calculator.currentCalculation),mocked:normalizeRequests(events.mocked),emails:await page.evaluate(()=>window.__emailMessages),dialogs:events.dialogs});await page.setViewportSize({width:1440,height:1000});await page.emulateMedia({media:'print'});await assets(page);await page.pdf({path:path.join(out,'specialty-calculators-screenprint-customer-'+name+'-'+phase+'.pdf'),format:'Letter',printBackground:true});}
for(const mode of ['empty','minimum','priced','form','success','failed-pricing','failed-session','failed-item','failed-setup','failed-email','failed-both'])test('CSS specialty customer-supplied screen print: '+mode,async({page})=>{
 const state={original,failedPricing:mode==='failed-pricing',failedSession:['failed-session','failed-both'].includes(mode),failedItem:mode==='failed-item',failedSetup:mode==='failed-setup',failedEmail:['failed-email','failed-both'].includes(mode)};
 const events=await ready(page,state);if(mode!=='empty')await configure(page,{quantity:mode==='minimum'?23:24});
 if(['form','success','failed-session','failed-item','failed-setup','failed-email','failed-both'].includes(mode))await fill(page);
 if(['success','failed-session','failed-item','failed-setup','failed-email','failed-both'].includes(mode)){await submit(page);if(mode!=='failed-both')await expect(page.locator('#successModal')).toBeVisible();else expect(events.dialogs).toContain('Failed to submit quote. Please try again or call (253) 922-5793.');}
 await evidence(page,mode,events);
});
test('CSS specialty customer-supplied screen print: all 396 quantity color and option results',async({page})=>{
 const events=await ready(page,{original});const values=await page.evaluate(async()=>{const calc=window.calculator,rows=[];for(const quantity of [23,24,47,48,71,72,144,145,576,577,1000])for(const frontColors of [1,3,6])for(const backColors of [0,2,6])for(const dark of [false,true])for(const stripes of [false,true]){const r=await calc.priceOrder(quantity,frontColors,backColors,dark,stripes);if(r.ok)calc.renderResult(quantity,frontColors,backColors,dark,stripes,r);rows.push({quantity,frontColors,backColors,dark,stripes,ok:r.ok,error:r.ok?null:r.error,calculation:r.ok?calc.currentCalculation:null,headline:r.ok?calc.priceDisplay.textContent:null,smallBatch:r.ok?document.getElementById('priceSmallBatchNote').textContent:null,summary:r.ok?calc.orderSummary.textContent.replace(/\s+/g,' ').trim():null});}return rows;});expect(values).toHaveLength(396);record('all-combinations',{values});check(expect,events);
});
for(const quantity of [24,145])test('CSS specialty customer-supplied screen print: saved invoice '+quantity,async({page})=>{
 const events=await ready(page,{original});await configure(page,{quantity});await fill(page);await submit(page);
 // Capture the original action's complete invoice HTML without opening the operating-system print dialog.
 await page.evaluate(()=>{window.__invoiceHTML='';window.open=()=>({document:{write:html=>{window.__invoiceHTML=html;},close:()=>{}},addEventListener:()=>{}});});
 await page.locator('#successModal [data-call="printQuote"]').click();const html=await page.evaluate(()=>window.__invoiceHTML);expect(html).toContain('<!DOCTYPE html>');
 const popup=await page.context().newPage();await popup.setContent(html.replace(/<script>\s*window.onload[\s\S]*?<\/script>/,''));await assets(popup);expect(await popup.title()).toContain('SPC0911-1');
 record('invoice-'+quantity,{title:await popup.title(),text:await popup.locator('body').innerText(),tables:await popup.locator('table').allTextContents()});await popup.screenshot({path:path.join(out,'specialty-calculators-screenprint-customer-invoice-'+quantity+'-'+phase+'-1440.png'),fullPage:true});await popup.pdf({path:path.join(out,'specialty-calculators-screenprint-customer-invoice-'+quantity+'-'+phase+'.pdf'),format:'Letter',printBackground:true});check(expect,events);await popup.close();
});
test('CSS specialty customer-supplied screen print: original pending edits retain stale quote and unsaved print does nothing',async({page})=>{
 test.skip(!original,'original defect evidence');const events=await ready(page,{original});await configure(page);await page.locator('#quoteActions [data-call="printQuote"]').click();expect(page.context().pages()).toHaveLength(1);expect(await page.evaluate(()=>window.__prints)).toEqual([]);
 const state=await page.evaluate(()=>{document.getElementById('quantity').value='145';document.getElementById('quantity').dispatchEvent(new Event('input',{bubbles:true}));return {input:document.getElementById('quantity').value,pricedQuantity:window.calculator.currentCalculation.quantity,actionsVisible:!!document.getElementById('quoteActions').getClientRects().length};});expect(state).toEqual({input:'145',pricedQuantity:24,actionsVisible:true});record('stale-input',{state});check(expect,events);
});
