const {test,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path'),AxeBuilder=require('@axe-core/playwright').default;
const {open,snapshot,check}=require('./helpers/calculator-reference-browser');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,'screenshots/css-unification'),capture=process.env.CAPTURE_CALCULATOR_REFERENCE_ORIGINAL==='1',phase=capture?'original':'current';
test.use({timezoneId:'America/Los_Angeles',locale:'en-US',reducedMotion:'reduce'});
async function evidence(page,name,events){const states=[];fs.mkdirSync(out,{recursive:true});
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(n=>n.decode().catch(()=>{})));});
 const s=await snapshot(page),axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();states.push({width,...s,violations:axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});
 if(!capture){expect(s.overflow).toBe(false);expect(axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);}
 await page.screenshot({path:path.join(out,'calculator-reference-'+name+'-'+phase+'-'+width+'.png'),fullPage:true});}
 check(expect,events);const record={name,states,dialogs:events.dialogs},file='tests/fixtures/calculator-reference-'+name+'-original-browser.json';
 if(capture){if(fs.existsSync(path.join(root,file)))expect(record).toEqual(JSON.parse(fs.readFileSync(path.join(root,file),'utf8')));else{fs.writeFileSync(path.join(root,file),JSON.stringify(record,null,2)+'\n');fs.appendFileSync(path.join(root,'ACTIVE_FILES.md'),'\n- '+file+' — immutable original synthetic calculator/reference browser contract.\n');}}
 else{const before=JSON.parse(fs.readFileSync(path.join(root,file),'utf8'));for(let i=0;i<states.length;i++)for(const key of ['title','url','ids','fields','links','tables','menu','rules','itemType','cost'])expect(states[i][key],name+' '+key).toEqual(before.states[i][key]);expect(events.dialogs).toEqual(before.dialogs);}
 await page.setViewportSize({width:1440,height:1000});await page.pdf({path:path.join(out,'calculator-reference-'+name+'-'+phase+'.pdf'),format:'Letter',printBackground:true});
}
async function manual(page,state={}){const e=await open(page,{...state,original:capture});await expect(page.locator('#blankCost')).toBeVisible();return e;}
async function calculate(page){await page.locator('#blankCost').fill('4.00');await page.locator('#calculateBtn').click();await expect(page.locator('.loading-spinner')).toHaveCount(0);await expect.poll(()=>page.locator('#dtgBody,#dtfBody,#embBody,#spBody').evaluateAll(ns=>ns.every(n=>n.querySelector('table,.card-error')))).toBe(true);}
test('CSS calculator reference: manual initial',async({page})=>{const e=await manual(page);await evidence(page,'manual-initial',e);});
test('CSS calculator reference: manual validation',async({page})=>{const e=await manual(page);await page.locator('#blankCost').fill('0');await page.locator('#blankCost').press('Enter');await expect(page.locator('#inputError')).toHaveClass(/visible/);await evidence(page,'manual-invalid-zero',e);await page.locator('#blankCost').fill('1000');await page.locator('#calculateBtn').click();await expect(page.locator('#inputError')).toContainText('unusually high');await evidence(page,'manual-invalid-high',e);});
test('CSS calculator reference: manual garment methods',async({page})=>{const e=await manual(page);await calculate(page);await expect(page.locator('#methodCards table')).toHaveCount(4);await evidence(page,'manual-garment',e);});
test('CSS calculator reference: manual garment options',async({page})=>{const e=await manual(page);await calculate(page);await page.locator('#dtgLocation').selectOption('FF');await page.locator('#dtgSecondLocation').check();await page.locator('#dtgSecondLocationSelect').selectOption('FB');await page.locator('#dtgLtmQty').fill('6');await page.locator('#dtgLtmQty').dispatchEvent('change');await page.locator('#dtfSecondLocation').check();await page.locator('#dtfLtmQty').fill('12');await page.locator('#dtfLtmQty').dispatchEvent('change');await page.locator('#embLtmQty').selectOption('3');await page.locator('#spColors').selectOption('2');await page.locator('#spLtmQty').fill('12');await page.locator('#spLtmQty').dispatchEvent('change');await evidence(page,'manual-options',e);});
test('CSS calculator reference: manual caps URL and quantity',async({page})=>{const e=await manual(page,{url:'/calculators/manual-pricing.html?manualCost=4&type=cap'});await expect(page.locator('#capEmbBody table')).toHaveCount(1);await evidence(page,'manual-cap',e);await page.locator('#capEmbLtmQty').selectOption('3');await evidence(page,'manual-cap-three',e);});
for(const failedMethod of ['all','DTG'])test('CSS calculator reference: manual failure '+failedMethod,async({page})=>{const e=await manual(page,{failed:failedMethod==='all',failedMethod});await calculate(page);await expect(page.locator('.card-error')).toHaveCount(failedMethod==='all'?4:1);await evidence(page,'manual-failed-'+failedMethod,e);});
test('CSS calculator reference: laser information',async({page})=>{const e=await open(page,{url:'/calculators/laser-manual-pricing.html',original:capture});await expect(page.locator('.coming-soon')).toContainText('Coming Soon!');await evidence(page,'laser',e);});
for(const mode of ['normal','long','failed','empty'])test('CSS calculator reference: shop menu '+mode,async({page})=>{const e=await open(page,{url:'/calculators/service-price-cheat-sheet.html',original:capture,failed:mode==='failed',empty:mode==='empty',long:mode==='long'});await expect(page.locator('#courses .course').first()).toBeVisible();await evidence(page,'menu-'+mode+'-rep',e);await page.locator('[data-view="customer"]').click();await expect(page.locator('body')).toHaveClass(/view-customer/);await evidence(page,'menu-'+mode+'-customer',e);});
test('CSS calculator reference: shop menu print view restoration',async({page})=>{const e=await open(page,{url:'/calculators/service-price-cheat-sheet.html',original:capture});await expect(page.locator('#courses .course').first()).toBeVisible();await page.locator('#printCustomerBtn').click();await expect.poll(()=>page.evaluate(()=>window.__printViews.length)).toBe(1);await expect(page.locator('body')).toHaveClass(/view-customer/);await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));await expect(page.locator('body')).toHaveClass(/view-rep/);await page.locator('[data-view="customer"]').click();await page.locator('#printRepBtn').click();await expect.poll(()=>page.evaluate(()=>window.__printViews.length)).toBe(2);await expect(page.locator('body')).toHaveClass(/view-rep/);await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));await expect(page.locator('body')).toHaveClass(/view-customer/);check(expect,e);});
