const {test,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path'),AxeBuilder=require('@axe-core/playwright').default;
const {ready,logo,products,variants}=require('./helpers/polar-camel-browser'),{snapshot,check}=require('./helpers/specialty-calculators-browser');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,'screenshots/css-unification'),original=process.env.CAPTURE_SPECIALTY_CALCULATORS_ORIGINAL==='1',phase=original?'original':'current';
test.use({timezoneId:'America/Los_Angeles',locale:'en-US',reducedMotion:'reduce'});
function record(name,value){const f='tests/fixtures/specialty-calculators-polar-camel-'+name+'-original-browser.json',full=path.join(root,f);if(original&&!fs.existsSync(full)){fs.writeFileSync(full,JSON.stringify(value,null,2)+'\n');fs.appendFileSync(path.join(root,'ACTIVE_FILES.md'),'\n- '+f+' — immutable synthetic Polar Camel browser and native financial evidence.\n');}else expect(value).toEqual(JSON.parse(fs.readFileSync(full,'utf8')));}
async function evidence(page,name,events){const states=[];fs.mkdirSync(out,{recursive:true});for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await page.evaluate(async()=>{scrollTo(0,document.body.scrollHeight);await document.fonts.ready;await Promise.all([...document.images].map(n=>n.decode().catch(()=>{})));scrollTo(0,0);});const state=await snapshot(page);delete state.ids['color-announcement'];const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();states.push({width,...state,violations:axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});if(!original){expect(state.overflow).toBe(false);expect(axe.violations).toEqual([]);}await page.screenshot({path:path.join(out,'specialty-calculators-polar-camel-'+name+'-'+phase+'-'+width+'.png'),fullPage:true});}check(expect,events);record(name,{states,mocked:events.mocked,dialogs:events.dialogs});await page.setViewportSize({width:1440,height:1000});await page.emulateMedia({media:'print'});await page.evaluate(async()=>{scrollTo(0,0);await document.fonts.ready;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});await page.pdf({path:path.join(out,'specialty-calculators-polar-camel-'+name+'-'+phase+'.pdf'),format:'Letter',printBackground:true});}
for(const mode of ['normal','zero-stock','failed-product','failed-policy','failed-inventory','logo','artwork-warning','lightbox'])test('CSS specialty Polar Camel: '+mode,async({page})=>{
 const events=await ready(page,{original,color:mode==='zero-stock'?'maroon':undefined,failedProduct:mode==='failed-product',failedPolicy:mode==='failed-policy',failedInventory:mode==='failed-inventory'});
 if(mode==='zero-stock')await page.locator('#ltmk-qty').fill('8');
 if(['logo','artwork-warning'].includes(mode)){await page.locator('#ltmk-file-input').setInputFiles(logo(mode==='artwork-warning'));await expect(page.locator('#ltmk-logo-name')).toContainText('sample-');if(mode==='logo'){await expect(page.locator('#ltmk-size-step')).toBeVisible();await page.locator('#ltmk-qty').fill('8');}else await expect(page.locator('#ltmk-warning')).toBeVisible();}
 if(mode==='lightbox')await page.locator('.gallery-thumbnail').first().click();
 await evidence(page,mode,events);
});
test('CSS specialty Polar Camel: mobile drawer',async({page})=>{const events=await ready(page,{original});await page.setViewportSize({width:390,height:1000});await page.locator('#mobileMenuBtn').click();await expect(page.locator('#sidebar')).toHaveClass(/show/);await evidence(page,'drawer',events);});
test('CSS specialty Polar Camel: all four colors and native tier boundaries',async({page})=>{
 const events=await ready(page,{original}),values=[];
 for(const [sku] of variants){if(sku!=='LTM752')await page.locator('label[for="color-'+sku+'"]').click();await expect(page.locator('#product-sku')).toHaveText(sku);await page.locator('#ltmk-preview-loading').waitFor({state:'hidden'});const table=await page.locator('.pricing-table').innerText(),inventory=await page.locator('#inventory-status').innerText();for(const qty of [1,11,12,23,24,119,120,239,240,479,480,959,960,9999,0,-1]){await page.locator('#ltmk-qty').fill(String(qty));values.push({sku,qty,table,inventory,quote:await page.locator('#ltmk-quote-result').innerText()});}}
 check(expect,events);record('tiers-colors',{values,mocked:events.mocked});
});
test('CSS specialty Polar Camel: real logo editing, errors and local PNG download',async({page})=>{
 const events=await ready(page,{original});await page.locator('#ltmk-file-input').setInputFiles(logo());await expect(page.locator('#ltmk-download-step')).toBeVisible();
 const canvas=page.locator('#ltmk-canvas'),before=await canvas.evaluate(n=>n.toDataURL());await canvas.focus();await page.keyboard.press('ArrowRight');expect(await canvas.evaluate(n=>n.toDataURL())).not.toEqual(before);await page.locator('#ltmk-center-btn').click();expect(await canvas.evaluate(n=>n.toDataURL())).toEqual(before);
 await page.locator('#ltmk-size-slider').fill('90');await expect(page.locator('#ltmk-size-pct')).toHaveText('90');await page.locator('#ltmk-fit-btn').click();const downloadEvent=page.waitForEvent('download');await page.locator('#ltmk-download-btn').click();const download=await downloadEvent;expect(download.suggestedFilename()).toBe('LTM752-sample_mark.png');const file=path.join(out,'specialty-calculators-polar-camel-download-'+phase+'.png');await download.saveAs(file);const bytes=fs.readFileSync(file);expect([bytes.readUInt32BE(16),bytes.readUInt32BE(20)]).toEqual([1800,1800]);
 await page.locator('#ltmk-logo-remove').click();await expect(page.locator('#ltmk-size-step')).toBeHidden();await expect(page.locator('#ltmk-download-step')).toBeHidden();await page.locator('#ltmk-file-input').setInputFiles({name:'invalid.png',mimeType:'image/png',buffer:Buffer.from('synthetic invalid image')});await expect(page.locator('#ltmk-preview-error')).toContainText("couldn't read");check(expect,events);
});
test('CSS specialty Polar Camel: cached product prices with altered live policy',async({page})=>{
 await page.addInitScript(({products})=>{sessionStorage.setItem('polar_camel_16oz_variants_v2',JSON.stringify({timestamp:Date.now(),products:products.map(p=>({...p,tiers:[{range:'1-11',quantity:11,customerPrice:19.5,description:'Small Order',handlingFee:50},{range:'12-23',quantity:23,customerPrice:19.5,description:'Small Order'},{range:'24-119',quantity:24,customerPrice:18.5,description:'Standard Order'},{range:'120-239',quantity:120,customerPrice:17.5,description:'Volume Order'},{range:'240+',quantity:240,customerPrice:16.5,description:'Bulk Order'}]}))}));},{products:products()});
 const events=await ready(page,{original,alternate:true,slowPolicy:true});await page.evaluate(()=>window.laserTumblerPage.apiService.ready);await page.locator('#ltmk-qty').fill('8');check(expect,events);record('cached-policy',{table:await page.locator('.pricing-table').innerText(),quote:await page.locator('#ltmk-quote-result').innerText(),mocked:events.mocked});
});
