/**
 * handbook-reader.js
 *
 * Fetches the Employee Handbook parent policy and all chapters from the
 * caspio-pricing-proxy public API, then renders them as a single-page
 * scrolling reader with sticky TOC sidebar and active-section highlighting.
 *
 * Architecture:
 *   - parent = policy with Policy_ID 'employee-handbook' (intro + about)
 *   - chapters = parent.children, sorted by Sort_Order
 *   - Each chapter is fetched individually because the tree endpoint
 *     strips Body_HTML to keep payload small.
 *   - Throttle: 4 parallel batches with 250ms gap to avoid 429 rate-limits.
 *   - PDF download button links to /forms/Employee-Handbook-Latest.pdf
 *     which is auto-generated by scripts/build-handbook-pdf.py
 *
 * Sync model: this page IS the live handbook. Edits to chapter policies
 * via the Policies Hub appear here on next page-load. To refresh the
 * downloadable PDF after a chapter edit, re-run the Python builder.
 */
(function () {
    'use strict';

    const PROXY = 'https://caspio-pricing-proxy-ab30a049961a.herokuapp.com';
    const PARENT_ID = 'employee-handbook';
    const BATCH_SIZE = 4;            // Parallel fetches per batch
    const BATCH_DELAY_MS = 250;       // Gap between batches to avoid 429

    const els = {
        content: document.getElementById('handbookContent'),
        toc: document.getElementById('handbookToc'),
        loadedAt: document.getElementById('handbookLoadedAt'),
        printBtn: document.getElementById('handbookPrintBtn'),
    };

    // ===== Utilities =====

    function cacheBust(url) {
        const sep = url.includes('?') ? '&' : '?';
        return `${url}${sep}_=${Date.now()}`;
    }

    async function fetchJSON(url) {
        const res = await fetch(cacheBust(url), { credentials: 'omit' });
        if (!res.ok) {
            throw new Error(`HTTP ${res.status} from ${url}`);
        }
        return res.json();
    }

    function sleep(ms) {
        return new Promise(r => setTimeout(r, ms));
    }

    function escapeHTML(s) {
        if (!s) return '';
        return String(s).replace(/[&<>"']/g, c => ({
            '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
        }[c]));
    }

    function fmtDate(s) {
        if (!s) return '';
        try {
            // Caspio Pacific timestamps come as naive ISO. Display as date only.
            const m = String(s).match(/^(\d{4})-(\d{2})-(\d{2})/);
            if (!m) return s;
            const d = new Date(`${m[1]}-${m[2]}-${m[3]}T12:00:00`);
            return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
        } catch (e) {
            return s;
        }
    }

    // Strip the web "Return to TOC" footer (everything after the last <hr>)
    // that CHAPTER_FOOTER injects via the policy detail view. The handbook
    // reader is the chapter list itself, so the footer is noise here.
    function stripChapterFooter(html) {
        if (!html) return '';
        const parts = html.split(/<hr\s*\/?>(?:\s*)/i);
        if (parts.length > 1) {
            return parts.slice(0, -1).join('<hr>');
        }
        return html;
    }

    // ===== Fetching =====

    async function fetchTree() {
        const data = await fetchJSON(`${PROXY}/api/policies-public/tree`);
        return data;
    }

    function findParentInTree(tree) {
        for (const cat of (tree.tree || [])) {
            for (const p of (cat.policies || [])) {
                if (p.Policy_ID === PARENT_ID) return p;
            }
        }
        return null;
    }

    async function fetchPolicy(policyId) {
        const data = await fetchJSON(`${PROXY}/api/policies-public/${encodeURIComponent(policyId)}`);
        return data.policy;
    }

    async function fetchChaptersInBatches(chapterIds) {
        const results = [];
        for (let i = 0; i < chapterIds.length; i += BATCH_SIZE) {
            const batch = chapterIds.slice(i, i + BATCH_SIZE);
            const fetched = await Promise.all(
                batch.map(id => fetchPolicy(id).catch(err => {
                    console.error(`Failed to fetch chapter ${id}:`, err);
                    return { Policy_ID: id, Title: id, Body_HTML: '<p><em>Failed to load this chapter. Try refreshing.</em></p>', _error: true };
                }))
            );
            results.push(...fetched);
            if (i + BATCH_SIZE < chapterIds.length) {
                await sleep(BATCH_DELAY_MS);
            }
        }
        return results;
    }

    // ===== Rendering =====

    function renderHero(parent) {
        const title = escapeHTML(parent.Title || 'Employee Handbook');
        const updated = parent.Updated_At ? fmtDate(parent.Updated_At) : '';
        return `
            <section class="handbook-hero">
                <h1>${title}</h1>
                <p class="handbook-hero-subtitle">Northwest Custom Apparel</p>
                <div class="handbook-hero-meta">
                    Effective May 26, 2026 ${updated ? `&middot; Last refreshed ${escapeHTML(updated)}` : ''}
                </div>
            </section>
        `;
    }

    function renderIntro(parent) {
        // Render parent body, but strip the explicit "Download PDF" link
        // since the topbar already has one (avoid duplication).
        let body = parent.Body_HTML || '';
        body = body.replace(
            /<h2>\s*Download a printable copy\s*<\/h2>\s*<p>[\s\S]*?<\/p>\s*(?:<p>[\s\S]*?<\/p>)?/i,
            ''
        );
        // Also strip the embedded Table of Contents (we render our own sticky TOC).
        body = body.replace(/<h2>\s*Table of Contents\s*<\/h2>\s*<ol>[\s\S]*?<\/ol>/i, '');
        body = stripChapterFooter(body);
        return `
            <section class="handbook-intro" id="handbook-intro">
                ${body}
            </section>
        `;
    }

    function renderChapter(ch, idx) {
        const title = escapeHTML(ch.Title || `Chapter ${idx + 1}`);
        const anchorId = `ch-${escapeHTML(ch.Policy_ID || idx)}`;
        const updated = ch.Updated_At ? fmtDate(ch.Updated_At) : '';
        const owner = ch.Owner_Name ? escapeHTML(ch.Owner_Name) : '';
        const detailUrl = `/pages/policy-detail.html?id=${encodeURIComponent(ch.Policy_ID)}`;
        const body = stripChapterFooter(ch.Body_HTML || '');

        return `
            <section class="handbook-chapter" id="${anchorId}" data-policy-id="${escapeHTML(ch.Policy_ID || '')}">
                <header class="handbook-chapter-header">
                    <h1 class="handbook-chapter-title">${title}</h1>
                    <div class="handbook-chapter-meta">
                        ${updated ? `<span><i class="far fa-clock"></i> Updated ${escapeHTML(updated)}</span>` : ''}
                        ${owner ? `<span><i class="far fa-user"></i> ${owner}</span>` : ''}
                        <span><a href="${detailUrl}" title="Open this chapter on its own page (with edit access for admins)"><i class="fas fa-external-link-alt"></i> Open in editor</a></span>
                    </div>
                </header>
                <div class="handbook-chapter-body">${body}</div>
            </section>
        `;
    }

    function renderTOC(chapters) {
        const items = [
            `<a href="#handbook-intro" class="handbook-toc-item" data-target="handbook-intro"><span class="handbook-toc-num">0.</span>About</a>`,
            ...chapters.map((ch, idx) => {
                const anchorId = `ch-${escapeHTML(ch.Policy_ID || idx)}`;
                // Title typically starts with "Chapter N: ..." — strip the leading "Chapter N: " for the TOC
                const cleanTitle = (ch.Title || '').replace(/^Chapter\s+\d+:\s*/i, '');
                return `<a href="#${anchorId}" class="handbook-toc-item" data-target="${anchorId}"><span class="handbook-toc-num">${idx + 1}.</span>${escapeHTML(cleanTitle || ch.Title || '')}</a>`;
            }),
        ];
        return items.join('');
    }

    // ===== Scroll-spy: highlight TOC item for current section =====

    function setupScrollSpy() {
        const sections = Array.from(document.querySelectorAll('.handbook-chapter, .handbook-intro'));
        const tocLinks = Array.from(document.querySelectorAll('.handbook-toc-item'));
        if (sections.length === 0 || tocLinks.length === 0) return;

        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    const id = entry.target.id;
                    tocLinks.forEach(a => {
                        a.classList.toggle('active', a.dataset.target === id);
                    });
                }
            });
        }, {
            rootMargin: '-15% 0px -70% 0px',  // Only the top portion counts as "in view"
            threshold: 0,
        });

        sections.forEach(s => observer.observe(s));
    }

    function setupBackToTop() {
        const btn = document.createElement('button');
        btn.className = 'handbook-back-top';
        btn.innerHTML = '<i class="fas fa-arrow-up"></i>';
        btn.title = 'Back to top';
        btn.setAttribute('aria-label', 'Back to top');
        btn.addEventListener('click', () => {
            window.scrollTo({ top: 0, behavior: 'smooth' });
        });
        document.body.appendChild(btn);

        window.addEventListener('scroll', () => {
            btn.classList.toggle('visible', window.scrollY > 400);
        }, { passive: true });
    }

    function setupPrintButton() {
        if (!els.printBtn) return;
        els.printBtn.addEventListener('click', () => {
            window.print();
        });
    }

    function setupSmoothScroll() {
        // Override default anchor behavior so links scroll smoothly and the
        // TOC active state has a moment to update.
        document.querySelectorAll('.handbook-toc-item').forEach(a => {
            a.addEventListener('click', (e) => {
                const targetId = a.dataset.target;
                if (!targetId) return;
                const target = document.getElementById(targetId);
                if (!target) return;
                e.preventDefault();
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
                // Update URL without jumping
                if (history.pushState) {
                    history.pushState(null, '', `#${targetId}`);
                }
            });
        });
    }

    // ===== Main =====

    function showError(msg) {
        els.content.innerHTML = `<div class="handbook-error">
            <strong>Could not load handbook.</strong> ${escapeHTML(msg)}
            <br><br>Try refreshing the page. If the problem persists, the Policies API may be down — check
            <a href="https://caspio-pricing-proxy-ab30a049961a.herokuapp.com/api/policies-public/tree" target="_blank">the API directly</a>.
        </div>`;
    }

    async function init() {
        try {
            const tree = await fetchTree();
            const parentStub = findParentInTree(tree);
            if (!parentStub) {
                showError(`Parent policy "${PARENT_ID}" not found in the policy tree.`);
                return;
            }

            // Sort children by Sort_Order
            const childIds = (parentStub.children || [])
                .slice()
                .sort((a, b) => (a.Sort_Order || 99999) - (b.Sort_Order || 99999))
                .map(c => c.Policy_ID);

            if (childIds.length === 0) {
                showError('No chapters found for the Employee Handbook.');
                return;
            }

            // Fetch parent + all children in parallel
            const [parent, ...chaptersUnsorted] = await Promise.all([
                fetchPolicy(PARENT_ID),
                ...(await fetchChaptersInBatches(childIds)).map(p => Promise.resolve(p)),
            ]);

            // Sort chapters by Sort_Order (their order should already match childIds, but be safe)
            const chapters = chaptersUnsorted.sort((a, b) => (a.Sort_Order || 99999) - (b.Sort_Order || 99999));

            // Render
            const html = [
                renderHero(parent),
                renderIntro(parent),
                ...chapters.map((ch, i) => renderChapter(ch, i)),
            ].join('\n');

            els.content.innerHTML = html;
            els.toc.innerHTML = renderTOC(chapters);

            if (els.loadedAt) {
                els.loadedAt.textContent = new Date().toLocaleString('en-US', {
                    month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit',
                });
            }

            // Wire up interactions
            setupScrollSpy();
            setupBackToTop();
            setupSmoothScroll();
            setupPrintButton();

            // If URL has a hash, jump to it after render
            if (window.location.hash) {
                const id = window.location.hash.slice(1);
                const target = document.getElementById(id);
                if (target) {
                    setTimeout(() => target.scrollIntoView({ behavior: 'smooth' }), 100);
                }
            }
        } catch (err) {
            console.error('Handbook reader init failed:', err);
            showError(err.message || 'Unknown error.');
        }
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
