/**
 * handbook-reader.js
 *
 * Fetches the Employee Handbook parent policy and all chapters from the
 * caspio-pricing-proxy public API, then renders them as a single-page
 * scrolling reader with sticky TOC sidebar and active-section highlighting.
 *
 * Architecture:
 *   - parent = policy with Policy_ID 'employee-handbook' (intro + about)
 *   - chapters = parent.children, sorted by Sort_Order
 *   - Each chapter is fetched individually because the tree endpoint
 *     strips Body_HTML to keep payload small.
 *   - Throttle: 4 parallel batches with 250ms gap to avoid 429 rate-limits.
 *   - PDF download button links to /forms/Employee-Handbook-Latest.pdf
 *     which is auto-generated by scripts/build-handbook-pdf.py
 *
 * Sync model: this page IS the live handbook. Edits to chapter policies
 * via the Policies Hub appear here on next page-load. To refresh the
 * downloadable PDF after a chapter edit, re-run the Python builder.
 */
(function () {
    'use strict';

    const PROXY = (typeof window !== 'undefined' && window.APP_CONFIG && window.APP_CONFIG.API && window.APP_CONFIG.API.BASE_URL) || '';
    if (!PROXY) console.error('[handbook-reader] APP_CONFIG.API.BASE_URL missing — the proxy host is not configured');
    const PARENT_ID = 'employee-handbook';
    const BATCH_SIZE = 4;            // Parallel fetches per batch
    const BATCH_DELAY_MS = 250;       // Gap between batches to avoid 429
    let scrollObserver;
    let printBound = false;

    const els = {
        content: document.getElementById('handbookContent'),
        toc: document.getElementById('handbookToc'),
        loadedAt: document.getElementById('handbookLoadedAt'),
        printBtn: document.getElementById('handbookPrintBtn'),
    };

    // ===== Utilities =====

    function cacheBust(url) {
        const sep = url.includes('?') ? '&' : '?';
        return `${url}${sep}_=${Date.now()}`;
    }

    async function fetchJSON(url) {
        const res = await fetch(cacheBust(url), { credentials: 'omit' });
        if (!res.ok) {
            throw new Error(`HTTP ${res.status} from ${url}`);
        }
        return res.json();
    }

    function sleep(ms) {
        return new Promise(r => setTimeout(r, ms));
    }

    function escapeHTML(s) {
        if (!s) return '';
        return String(s).replace(/[&<>"']/g, c => ({
            '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
        }[c]));
    }

    function fmtDate(s) {
        if (!s) return '';
        try {
            // Caspio Pacific timestamps come as naive ISO. Display as date only.
            const m = String(s).match(/^(\d{4})-(\d{2})-(\d{2})/);
            if (!m) return s;
            const d = new Date(`${m[1]}-${m[2]}-${m[3]}T12:00:00`);
            return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
        } catch (e) {
            return s;
        }
    }

    // Remove only a trailing navigation footer; an ordinary final section after a rule is content.
    function stripChapterFooter(html) {
        if (!html) return '';
        return html.replace(/<hr\s*\/?>(?:\s*)<p\b[^>]*>(?:(?!<\/p>)[\s\S])*?(?:Return to (?:TOC|Table of Contents)|Back to Table of Contents)(?:(?!<\/p>)[\s\S])*?<\/p>\s*$/i, '');
    }

    function sanitizeContent(html) {
        if (!window.DOMPurify) throw new Error('Handbook content could not be prepared safely. Please reload.');
        const clean = window.DOMPurify.sanitize(html, {
            ADD_TAGS: ['iframe'],
            ADD_ATTR: ['target', 'rel', 'allow', 'allowfullscreen', 'frameborder', 'loading', 'data-video-embed', 'data-src', 'data-kind'],
            FORBID_TAGS: ['style', 'script'],
        });
        const wrapper = document.createElement('div');
        // eslint-disable-next-line no-unsanitized/property -- DOMPurify sanitized this markup; trusted video URLs are checked next.
        wrapper.innerHTML = clean;
        wrapper.querySelectorAll('iframe').forEach(frame => {
            if (!/^https:\/\/(?:www\.)?(youtube\.com|youtube-nocookie\.com|loom\.com|player\.vimeo\.com)\//.test(frame.getAttribute('src') || '')) frame.remove();
        });
        return wrapper.innerHTML;
    }

    // ===== Fetching =====

    async function fetchTree() {
        const data = await fetchJSON(`${PROXY}/api/policies-public/tree`);
        return data;
    }

    function findParentInTree(tree) {
        for (const cat of (tree.tree || [])) {
            for (const p of (cat.policies || [])) {
                if (p.Policy_ID === PARENT_ID) return p;
            }
        }
        return null;
    }

    async function fetchPolicy(policyId) {
        const data = await fetchJSON(`${PROXY}/api/policies-public/${encodeURIComponent(policyId)}`);
        if (!data?.policy || typeof data.policy.Body_HTML !== 'string') throw new Error('Unexpected chapter response');
        return data.policy;
    }

    async function fetchChaptersInBatches(chapterIds) {
        const results = [];
        for (let i = 0; i < chapterIds.length; i += BATCH_SIZE) {
            const batch = chapterIds.slice(i, i + BATCH_SIZE);
            const fetched = await Promise.all(
                batch.map(id => fetchPolicy(id).catch(err => {
                    console.error(`Failed to fetch chapter ${id}:`, err);
                    return { Policy_ID: id, Title: id, Body_HTML: '<p><em>Failed to load this chapter. Try refreshing.</em></p>', _error: true };
                }))
            );
            results.push(...fetched);
            if (i + BATCH_SIZE < chapterIds.length) {
                await sleep(BATCH_DELAY_MS);
            }
        }
        return results;
    }

    // ===== Rendering =====

    function renderHero(parent) {
        const title = escapeHTML(parent.Title || 'Employee Handbook');
        const updated = parent.Updated_At ? fmtDate(parent.Updated_At) : '';
        return `
            <section class="handbook-hero">
                <h2 class="handbook-doc-title">${title}</h2>
                <p class="handbook-hero-subtitle">Northwest Custom Apparel</p>
                <div class="handbook-hero-meta">
                    Effective May 26, 2026 ${updated ? `&middot; Last refreshed ${escapeHTML(updated)}` : ''}
                </div>
            </section>
        `;
    }

    function renderIntro(parent) {
        // Render parent body, but strip the duplicate download/read links
        // (the topbar already has both buttons) and the embedded TOC
        // (we render our own sticky TOC sidebar).
        let body = parent.Body_HTML || '';
        // Match both the legacy "Download a printable copy" heading and the
        // current "Read or download the handbook" heading. Each is followed
        // by 1-3 short paragraphs that we also strip.
        body = body.replace(
            /<h2>\s*(?:Download a printable copy|Read or download the handbook)\s*<\/h2>(?:\s*<p>[\s\S]*?<\/p>){1,3}/gi,
            ''
        );
        // Strip the embedded Table of Contents (we render our own sticky TOC).
        body = body.replace(/<h2>\s*Table of Contents\s*<\/h2>\s*<ol>[\s\S]*?<\/ol>/i, '');
        body = stripChapterFooter(body);
        return `
            <section class="handbook-intro" id="handbook-intro">
                ${body}
            </section>
        `;
    }

    function renderChapter(ch, idx) {
        const title = escapeHTML(ch.Title || `Chapter ${idx + 1}`);
        const anchorId = `ch-${escapeHTML(ch.Policy_ID || idx)}`;
        const updated = ch.Updated_At ? fmtDate(ch.Updated_At) : '';
        const owner = ch.Owner_Name ? escapeHTML(ch.Owner_Name) : '';
        const detailUrl = `/pages/policy-detail.html?id=${encodeURIComponent(ch.Policy_ID)}`;
        const body = stripChapterFooter(ch.Body_HTML || '');

        return `
            <section class="handbook-chapter" id="${anchorId}" data-policy-id="${escapeHTML(ch.Policy_ID || '')}">
                <header class="handbook-chapter-header">
                    <h2 class="handbook-chapter-title">${title}</h2>
                    <div class="handbook-chapter-meta">
                        ${updated ? `<span><i class="far fa-clock" aria-hidden="true"></i> Updated ${escapeHTML(updated)}</span>` : ''}
                        ${owner ? `<span><i class="far fa-user" aria-hidden="true"></i> ${owner}</span>` : ''}
                        <span><a href="${detailUrl}" title="Open this chapter on its own page (with edit access for admins)"><i class="fas fa-external-link-alt" aria-hidden="true"></i> Open in editor</a></span>
                    </div>
                </header>
                <div class="handbook-chapter-body">${body}</div>
            </section>
        `;
    }

    function renderTOC(chapters) {
        const items = [
            `<a href="#handbook-intro" class="handbook-toc-item" data-target="handbook-intro"><span class="handbook-toc-num">0.</span>About</a>`,
            ...chapters.map((ch, idx) => {
                const anchorId = `ch-${escapeHTML(ch.Policy_ID || idx)}`;
                // Title typically starts with "Chapter N: ..." — strip the leading "Chapter N: " for the TOC
                const cleanTitle = (ch.Title || '').replace(/^Chapter\s+\d+:\s*/i, '');
                return `<a href="#${anchorId}" class="handbook-toc-item" data-target="${anchorId}"><span class="handbook-toc-num">${idx + 1}.</span>${escapeHTML(cleanTitle || ch.Title || '')}</a>`;
            }),
        ];
        return items.join('');
    }

    // ===== Scroll-spy: highlight TOC item for current section =====

    function setupScrollSpy() {
        scrollObserver?.disconnect();
        const sections = Array.from(document.querySelectorAll('.handbook-chapter, .handbook-intro'));
        const tocLinks = Array.from(document.querySelectorAll('.handbook-toc-item'));
        if (sections.length === 0 || tocLinks.length === 0) return;

        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    const id = entry.target.id;
                    tocLinks.forEach(a => {
                        a.classList.toggle('active', a.dataset.target === id);
                    });
                }
            });
        }, {
            rootMargin: '-15% 0px -70% 0px',  // Only the top portion counts as "in view"
            threshold: 0,
        });

        sections.forEach(s => observer.observe(s));
        scrollObserver = observer;
    }

    function setupBackToTop() {
        if (document.querySelector('.handbook-back-top')) return;
        const btn = document.createElement('button');
        btn.className = 'handbook-back-top';
        btn.innerHTML = '<i class="fas fa-arrow-up" aria-hidden="true"></i>';
        btn.title = 'Back to top';
        btn.setAttribute('aria-label', 'Back to top');
        btn.addEventListener('click', () => {
            const title = document.querySelector('.handbook-topbar-title');
            title.tabIndex = -1; title.focus({ preventScroll: true });
            window.scrollTo({ top: 0, behavior: 'auto' });
        });
        document.body.appendChild(btn);

        window.addEventListener('scroll', () => {
            btn.classList.toggle('visible', window.scrollY > 400);
        }, { passive: true });
    }

    function setupPrintButton() {
        if (!els.printBtn || printBound) return;
        printBound = true;
        els.printBtn.addEventListener('click', () => {
            window.print();
        });
    }

    function setupSmoothScroll() {
        // Native fragment navigation preserves keyboard focus and browser history.
        document.querySelectorAll('.handbook-toc-item').forEach(a => {
            const target = document.getElementById(a.dataset.target);
            if (target) target.tabIndex = -1;
        });
    }

    // ===== Main =====

    function showError(msg) {
        els.content.innerHTML = `<div class="handbook-error" role="alert">
            <strong>Could not load handbook.</strong> ${escapeHTML(msg)}
            <p><button type="button" class="btn">Retry</button></p>
        </div>`;
        els.content.querySelector('button').addEventListener('click', init);
    }

    async function init() {
        els.printBtn.disabled = true;
        els.content.setAttribute('aria-busy', 'true');
        try {
            const tree = await fetchTree();
            const parentStub = findParentInTree(tree);
            if (!parentStub) {
                showError(`Parent policy "${PARENT_ID}" not found in the policy tree.`);
                return;
            }

            // Sort children by Sort_Order
            const childIds = (parentStub.children || [])
                .slice()
                .sort((a, b) => (a.Sort_Order || 99999) - (b.Sort_Order || 99999))
                .map(c => c.Policy_ID);

            if (childIds.length === 0) {
                showError('No chapters found for the Employee Handbook.');
                return;
            }

            // Fetch parent + all children in parallel
            const [parent, ...chaptersUnsorted] = await Promise.all([
                fetchPolicy(PARENT_ID),
                ...(await fetchChaptersInBatches(childIds)).map(p => Promise.resolve(p)),
            ]);

            // Sort chapters by Sort_Order (their order should already match childIds, but be safe)
            const chapters = chaptersUnsorted.sort((a, b) => (a.Sort_Order || 99999) - (b.Sort_Order || 99999));

            // Render
            const html = [
                renderHero(parent),
                renderIntro(parent),
                ...chapters.map((ch, i) => renderChapter(ch, i)),
            ].join('\n');

            // eslint-disable-next-line no-unsanitized/property -- Policy markup has passed DOMPurify and the trusted-video allowlist; sanitizer failure stops rendering.
            els.content.innerHTML = sanitizeContent(html);
            // eslint-disable-next-line no-unsanitized/property -- Composed UI markup: external labels are escaped or encoded; other values are fixed markup or numeric counts.
            els.toc.innerHTML = renderTOC(chapters);
            const missing = chapters.filter(ch => ch._error).length;
            if (missing) {
                const warning = document.createElement('div'); warning.className = 'handbook-error'; warning.setAttribute('role', 'alert');
                const message = document.createElement('p'); message.textContent = missing + ' chapter(s) could not load. This handbook is incomplete.';
                const retry = document.createElement('button'); retry.type = 'button'; retry.className = 'btn'; retry.textContent = 'Retry missing chapters'; retry.addEventListener('click', init);
                warning.append(message, retry); els.content.prepend(warning);
            }
            els.printBtn.disabled = false;

            if (els.loadedAt) {
                els.loadedAt.textContent = new Date().toLocaleString('en-US', {
                    month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit',
                });
            }

            // Wire up interactions
            setupScrollSpy();
            setupBackToTop();
            setupSmoothScroll();
            setupPrintButton();

            // If URL has a hash, jump to it after render
            if (window.location.hash) {
                const id = window.location.hash.slice(1);
                const target = document.getElementById(id);
                if (target) {
                    target.focus({ preventScroll: true }); target.scrollIntoView({ behavior: 'auto' });
                }
            }
        } catch (err) {
            console.error('Handbook reader init failed:', err);
            showError(err.message || 'Unknown error.');
        } finally {
            els.content.setAttribute('aria-busy', 'false');
        }
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
