/**
 * design-queue.js — controller for dashboards/design-queue.html
 *
 * Tells Steve which South Sound subject to draw next, and why.
 *
 * WHY THE DATA IS A STATIC FILE, not Caspio and not an API. Caspio is metered per
 * call and this account has already taken a $358 overage; a dashboard Steve opens
 * daily has no business spending quota to read 70 rows that change monthly. The
 * file is regenerated by 253gear-growth/scripts/build-design-queue.js and ships
 * with the deploy, so the page costs nothing to open and works if the proxy is down.
 *
 * THE RANKING RULE. A subject needs an empty seat AND living memory — both, not
 * either. Vacancy does the heavy lifting: across the 47 live products, vacancy >=14
 * ranks 44% of the time against 16% below it, while nostalgia barely separates the
 * groups at all. Bob's Java Jive is the proof in one direction — maximum affection,
 * vacancy 3, does not rank, because the news already told that story.
 *
 * But vacancy alone sends Steve to draw a hotel that closed in 1923. Hotel Hesperides
 * scores vacancy 17 and nostalgia 6: almost nobody has written about it, and almost
 * nobody remembers it either. Hence two thresholds, not one.
 */
(function () {
    'use strict';

    var DATA_URL = '/dashboards/data/design-queue.json';

    var VERDICT = {
        draw:     { label: 'Draw this',     cls: 'dq-chip--draw' },
        research: { label: 'Research first', cls: 'dq-chip--research' },
        skip:     { label: 'Skip',          cls: 'dq-chip--skip' }
    };

    var state = { data: null, filter: 'all' };

    document.addEventListener('DOMContentLoaded', function () {
        load().catch(function (err) {
            console.error('[design-queue] load failed:', err);
            // Never fall back to stale or invented rows — a wrong queue sends Steve
            // to draw the wrong thing, which costs a day.
            DashPage.showError('Unable to load the design queue. Refresh, and if it persists the data file may not have deployed.');
            setText('queue-root', '');
            setText('catalogue-root', '');
        });
    });

    async function load() {
        var res = await fetch(DATA_URL + '?v=' + Date.now(), { cache: 'no-store' });
        if (!res.ok) throw new Error('HTTP ' + res.status + ' for ' + DATA_URL);
        var data = await res.json();
        if (!data || !Array.isArray(data.candidates)) throw new Error('malformed queue data');

        state.data = data;
        renderStats(data);
        renderFilters();
        renderQueue();
        renderCatalogue(data);
        renderProvenance(data);
    }

    /**
     * A subject needs BOTH axes. Vacancy alone is not enough, and the candidate
     * scoring proved it: Hotel Hesperides scores vacancy 17 — almost nobody has
     * written about it — but nostalgia 6, because it closed in 1923 and nobody
     * alive remembers it. An empty seat nobody searches is still nobody. The
     * mirror case is Never Never Land: nostalgia 19, vacancy 3, because Threadless
     * and a local rival already sell it.
     *
     * So: empty seat AND living memory. Either one alone is a "research first".
     */
    var VACANT = 12;      // below this, somebody already owns the answer
    var REMEMBERED = 12;  // below this, the cohort that remembers is too small or gone

    function verdictOf(row) {
        if (row.trademark === 'live') return 'research';
        if (row.stillTrading) return 'research';           // licensing talk, not a free design
        if (row.templatable) return 'skip';                // a marketplace swaps the city name and wins
        if (row.competitorType === 'marketplace') return 'skip';
        if (row.competitorType === 'unrelated-collision') return 'skip';
        if (row.vacancy >= VACANT && row.nostalgia >= REMEMBERED) return 'draw';
        if (row.vacancy >= VACANT || row.nostalgia >= REMEMBERED) return 'research';
        return 'skip';
    }

    /** Why this row got its verdict, in Steve's terms rather than the model's. */
    function verdictReason(row) {
        if (row.trademark === 'live') return 'Live trademark — needs a look before anything is drawn.';
        if (row.stillTrading) return 'Still trading. Ask them first — a link from their site beats the margin on the shirt.';
        if (row.templatable) return 'A marketplace can sell this by swapping in another city. We lose on their turf.';
        if (row.competitorType === 'marketplace') return 'Etsy, Redbubble or Amazon already own this term.';
        if (row.competitorType === 'unrelated-collision') return 'The name collides with something bigger — it cannot rank whatever we do.';
        if (row.vacancy >= VACANT && row.nostalgia >= REMEMBERED) return 'Empty seat, and people still remember it. This is the shape that worked for Clyde\'s.';
        if (row.vacancy >= VACANT) return 'The seat is empty — but the people who remember it are largely gone. Check anyone still searches.';
        if (row.nostalgia >= REMEMBERED) return 'Well remembered, but somebody already wrote the page. Winnable only with something they do not have.';
        return 'Neither empty nor strongly remembered.';
    }

    function renderStats(data) {
        var v = data.candidates.map(verdictOf);
        setText('stat-draw', String(v.filter(function (x) { return x === 'draw'; }).length));
        setText('stat-research', String(v.filter(function (x) { return x === 'research'; }).length));
        setText('stat-skip', String(v.filter(function (x) { return x === 'skip'; }).length));
        setText('stat-checked', String(data.candidates.length + (data.catalogue || []).length));
    }

    function renderFilters() {
        var root = document.getElementById('dq-filters');
        if (!root) return;
        var opts = [
            { key: 'all', label: 'All' },
            { key: 'draw', label: 'Draw this' },
            { key: 'research', label: 'Research first' },
            { key: 'skip', label: 'Skip' }
        ];
        root.innerHTML = '';
        opts.forEach(function (o) {
            var b = document.createElement('button');
            b.type = 'button';
            b.className = 'dq-filter';
            b.textContent = o.label;
            b.setAttribute('aria-pressed', String(state.filter === o.key));
            b.addEventListener('click', function () {
                state.filter = o.key;
                renderFilters();
                renderQueue();
            });
            root.appendChild(b);
        });
    }

    function renderQueue() {
        var root = document.getElementById('queue-root');
        if (!root || !state.data) return;
        root.classList.remove('dash-loading');

        var rows = state.data.candidates
            .map(function (r) { return Object.assign({}, r, { verdict: verdictOf(r) }); })
            .filter(function (r) { return state.filter === 'all' || r.verdict === state.filter; })
            .sort(function (a, b) { return b.vacancy - a.vacancy; });

        if (!rows.length) {
            root.innerHTML = '';
            root.appendChild(el('div', 'dq-empty', 'Nothing in this group.'));
            return;
        }
        root.innerHTML = '';
        var list = el('div', 'dq-list');
        rows.forEach(function (r) { list.appendChild(rowEl(r)); });
        root.appendChild(list);
    }

    function rowEl(r) {
        var row = el('div', 'dq-row' + (r.verdict === 'skip' ? ' dq-row--skip' : ''));

        var v = VERDICT[r.verdict];
        row.appendChild(el('span', 'dq-chip ' + v.cls, v.label));

        var subj = el('div', 'dq-subject');
        subj.appendChild(document.createTextNode(r.subject));
        if (r.city) {
            var c = el('span', 'dq-city', '  ' + r.city);
            subj.appendChild(c);
        }
        row.appendChild(subj);

        var score = el('div', 'dq-score');
        score.appendChild(el('div', 'dq-score-value', String(r.vacancy)));
        score.appendChild(el('div', 'dq-score-label', 'vacancy'));
        row.appendChild(score);

        row.appendChild(el('div', 'dq-reason', verdictReason(r)));
        if (r.heldBy) row.appendChild(el('div', 'dq-reason', 'Best result now: ' + r.heldBy));

        var flags = el('div', 'dq-flags');
        if (r.templatable) flags.appendChild(el('span', 'dq-flag dq-flag--warn', 'a marketplace can template this'));
        if (r.stillTrading) flags.appendChild(el('span', 'dq-flag dq-flag--warn', 'still trading — ask first'));
        if (r.trademark === 'live') flags.appendChild(el('span', 'dq-flag dq-flag--warn', 'live trademark'));
        if (r.heldBy) flags.appendChild(el('span', 'dq-flag', 'seat held by: ' + r.heldBy));
        if (r.alreadyRanks) flags.appendChild(el('span', 'dq-flag', 'we already rank'));
        if (flags.childNodes.length) row.appendChild(flags);

        return row;
    }

    function heldBy(r) {
        var map = {
            nothing: 'Nothing indexable about this at all — the seat is completely empty.',
            'social-post': 'The best result is a social post. Nobody has written the page.',
            forum: 'A forum thread is the best that exists.',
            'local-blog-or-archive': 'A local blog or archive got there first. Winnable only with something they do not have.',
            news: 'A news outlet already told this story.',
            wikipedia: 'An encyclopedia owns the subject.',
            marketplace: 'Etsy, Redbubble or Amazon own this term. We lose on their turf.',
            'national-brand': 'A national brand owns the name.',
            'unrelated-collision': 'The name collides with something bigger — it cannot rank whatever we do.'
        };
        return map[r.competitorType] || '';
    }

    function renderCatalogue(data) {
        var root = document.getElementById('catalogue-root');
        if (!root) return;
        root.classList.remove('dash-loading');
        var cat = (data.catalogue || [])
            .filter(function (r) { return r.vacancy >= 8; })
            .sort(function (a, b) { return b.vacancy - a.vacancy; });

        root.innerHTML = '';
        if (!cat.length) {
            root.appendChild(el('div', 'dq-empty', 'No existing product is sitting in a winnable seat.'));
            return;
        }
        var list = el('div', 'dq-list');
        cat.forEach(function (r) {
            var row = el('div', 'dq-row');
            var thin = r.words < 300;
            row.appendChild(el('span', 'dq-chip ' + (thin ? 'dq-chip--draw' : 'dq-chip--skip'),
                thin ? 'Add words' : 'Done'));
            row.appendChild(el('div', 'dq-subject', r.subject));
            var score = el('div', 'dq-score');
            score.appendChild(el('div', 'dq-score-value', String(r.vacancy)));
            score.appendChild(el('div', 'dq-score-label', 'vacancy'));
            row.appendChild(score);
            row.appendChild(el('div', 'dq-reason',
                r.words + ' words of body copy' + (thin ? ' — under 300, and the words are what rank.' : ' — long enough.')
                + (r.alreadyRanks ? ' Already ranking.' : '')));
            list.appendChild(row);
        });
        root.appendChild(list);
    }

    function renderProvenance(data) {
        var p = document.getElementById('dq-provenance');
        if (!p) return;
        p.textContent = 'Vacancy scored by searching each subject name and reading what already ranks — '
            + 'no keyword tool reports volume this small. Checked ' + (data.generatedAt || 'recently')
            + '. Regenerate with build-design-queue.js in the 253gear-growth repo. '
            + 'Verdicts are guidance, not gospel — if you know something the search does not, you are right and it is wrong.';
    }

    /* helpers — textContent only, never innerHTML with data (CLAUDE.md XSS rule) */
    function el(tag, cls, text) {
        var n = document.createElement(tag);
        if (cls) n.className = cls;
        if (text != null) n.textContent = text;
        return n;
    }

    function setText(id, text) {
        var n = document.getElementById(id);
        if (n) { n.textContent = text; n.classList.remove('dash-loading'); }
    }
})();
